version: 2.1
orbs:
  jq: circleci/jq@2.2.0
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/keitaro1020/circleci_githubapps_practice
    steps:
      - checkout
      - run:
          name: build
          command: |
            go get -v -t -d ./...
            go test -v ./...
            make build
            mkdir -p /tmp/work/build
            cp -pr ./bin /tmp/work/build
            ls -lR /tmp/work
      - persist_to_workspace:
          root: /tmp/work/
          paths:
            - ./*
  download_github_release:
    docker:
      - image: circleci/golang:latest
    steps:
      - attach_workspace:
          at: /tmp/work
      - run:
          name: download_github_release
          command: |
            go get github.com/github-release/github-release
            cp /go/bin/github-release /tmp/work/
      - persist_to_workspace:
          root: /tmp/work/
          paths:
            - ./github-release
  release:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/work
      - run:
          name: release
          command: |
            cp -pr /tmp/work/build/bin .
            cp -pr /tmp/work/github-release .
            zip -r release.zip ./bin
            cd scripts
            echo $GITHUB_APPS_PEM_BASE64 | base64 --decode > ./private.pem
            bundle install --path vendor/bundle
            GITHUB_APP_JWT=`ruby ./get_jws.rb`
            export GITHUB_TOKEN=`curl -X POST \
              -H "Authorization: Bearer $GITHUB_APP_JWT" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/app/installations/13706525/access_tokens | jq .token | sed 's/\"//g'`
            echo $CIRCLE_TAG
            ../github-release upload \
              --user keitaro1020 \
              --repo circleci_githubapps_practice
              --tag ${CIRCLE_TAG} \
              --name "release_bin.zip" \
              --file ./release.zip

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.+$/
      - download_github_release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.+$/
      - release:
          requires:
            - download_github_release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.+$/
