version: 2.1
orbs:
  jq: circleci/jq@2.2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/keitaro1020/circleci_githubapps_practice
    steps:
      - checkout
      - run:
          name: build
          command: |
            go get -v -t -d ./...
            go test -v ./...
            make build
            mkdir -p /tmp/build
            cp -pr ./bin /tmp/build
            ls -lR /tmp/build
      - persist_to_workspace:
          root: /tmp/build
          paths:
            - ./*
  release:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build
      - run:
          name: release
          command: |
            cp -pr /tmp/build/bin .
            cd scripts
            echo $GITHUB_APPS_PEM_BASE64 | base64 --decode > ./private.pem
            bundle install --path vendor/bundle
            GITHUB_APP_JWT=`ruby ./get_jws.rb`
            echo $GITHUB_APP_JWT
            GITHUB_TOKEN = `curl -X POST \
              -H "Authorization: Bearer $GITHUB_APP_JWT" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/app/installations/13706525/access_tokens | jq .token`
            echo $GITHUB_TOKEN

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.+$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.+$/
