version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/keitaro1020/circleci_githubapps_practice
    steps:
      - checkout
      - run:
          name: build
          command: |
            go get -v -t -d ./...
            go test -v ./...
            make build
            mkdir -p /tmp/build
            cp -pr ./bin /tmp/build
            ls -lR /tmp/build
      - persist_to_workspace:
          root: /tmp/build
          paths:
            - ./*
  release:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build
      - run:
          name: release
          command: |
            cp -pr /tmp/build/bin .
            echo $GITHUB_APPS_PEM_BASE64 | base64 --decode > ./scripts/private.pem
            ruby ./scripts/get_jws.rb
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
          filters:
            tags:
              only: /^v.+$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.+$/
