version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/keitaro1020/circleci_githubapps_practice
    steps:
      - checkout
      - run:
          name: build
          command: |
            go get -v -t -d ./...
            go test -v ./...
            make build
            ls
      - persist_to_workspace:
          root: /go/src/github.com/keitaro1020/circleci_githubapps_practice
          paths:
            - ./*
  release:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/keitaro1020/circleci_githubapps_practice
    steps:
      - attach_workspace:
          at: /go/src/github.com/keitaro1020/circleci_githubapps_practice
      - run:
          name: release
          command: |
            echo $GITHUB_APPS_PRIVATE_PEM > private.pem
            wc -l private.pem
            ls
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
